# Generated by Django 4.2.11 on 2024-04-13 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0011_usuario_image'),
        ('desprendible', '0001_initial'),
    ]


