# Generated by Django 5.0.4 on 2024-04-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desprendible', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descuento',
            name='desc_total_parcial_des',
        ),
    ]
