# Generated by Django 5.0.3 on 2024-05-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desprendible', '0004_remove_descuento_desc_total_parcial_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuento',
            name='des_time_retardo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
