# Generated by Django 5.0.4 on 2024-05-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desprendible', '0006_valores_fijos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valores_fijos',
            name='valor_aport_icbf',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='valores_fijos',
            name='valor_aport_pension',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='valores_fijos',
            name='valor_aport_salud',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='valores_fijos',
            name='valor_aport_sena',
            field=models.FloatField(),
        ),
    ]
