# Generated by Django 5.0.4 on 2024-05-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desprendible', '0009_descuento_total_descuentos_nomina_total_neto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='total_descuentos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='devengado',
            name='total_devengados',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='total_neto',
            field=models.IntegerField(null=True),
        ),
    ]
