# Generated by Django 5.0.3 on 2024-06-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desprendible', '0010_alter_descuento_total_descuentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='estado',
            field=models.CharField(default='pendiente', max_length=50),
        ),
    ]
