# Generated by Django 4.2.11 on 2024-06-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desprendible', '0011_nomina_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='devengado',
            name='deveng_tipo_descuento',
            field=models.TextField(default='fiscal', max_length=50),
        ),
    ]
