# Generated by Django 5.0.3 on 2024-03-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0005_alter_usuario_usu_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="usu_telefono",
            field=models.IntegerField(max_length=10),
        ),
    ]
