# Generated by Django 5.0.3 on 2024-03-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0006_alter_usuario_usu_telefono"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
