# Generated by Django 5.0.3 on 2024-03-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0010_alter_usuario_usu_telefono"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
