# Generated by Django 5.0.3 on 2024-03-11 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="usu_antiguedad",
        ),
        migrations.AlterField(
            model_name="usuario",
            name="usu_fecha_ingreso",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="usu_id_rol",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="usuario.rol"
            ),
        ),
    ]
