# Generated by Django 5.0.3 on 2024-03-11 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0003_alter_usuario_usu_id_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="usu_id_rol",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="usuario.rol"
            ),
        ),
    ]
