# Generated by Django 5.0.3 on 2024-03-12 01:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0007_usuario_last_login"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="usu_cedula",
            new_name="cedula",
        ),
        migrations.RenameField(
            model_name="usuario",
            old_name="usu_contraseña",
            new_name="password",
        ),
    ]
