# Generated by Django 5.0.3 on 2024-03-12 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0008_rename_usu_cedula_usuario_cedula_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="usu_id_rol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usuario.rol"
            ),
        ),
    ]
