# Generated by Django 5.0.3 on 2024-03-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0009_alter_usuario_usu_id_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="usu_telefono",
            field=models.IntegerField(),
        ),
    ]
