# Generated by Django 5.0.4 on 2024-04-17 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desprendible', '0002_initial'),
        ('usuario', '0011_usuario_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('desc_id', models.AutoField(primary_key=True, serialize=False)),
                ('desc_creditos_libranza', models.IntegerField()),
                ('desc_cuotas_sindicales', models.IntegerField()),
                ('desc_embargos_judiciales', models.IntegerField()),
                ('desc_periodo_pago', models.DateField()),
                ('desc_tipo_descuento', models.TextField()),
                ('desc_precio', models.IntegerField()),
                ('desc_fecha_des', models.DateField()),
                ('desc_total_parcial_des', models.IntegerField()),
                ('desc_cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario', to_field='cedula')),
            ],
        ),
        migrations.CreateModel(
            name='Devengado',
            fields=[
                ('deveng_id', models.AutoField(primary_key=True, serialize=False)),
                ('deveng_subs_trans', models.IntegerField()),
                ('deveng_subs_alim', models.IntegerField()),
                ('deveng_horas_extra_diur', models.IntegerField()),
                ('deveng_horas_extra_noct', models.IntegerField()),
                ('deveng_horas_extra_diur_domfest', models.IntegerField()),
                ('deveng_horas_extra_noct_domfest', models.IntegerField()),
                ('deveng_bonificacion', models.IntegerField()),
                ('deveng_periodo_pago', models.DateField()),
                ('deveng_fecha', models.DateField()),
                ('deveng_cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario', to_field='cedula')),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('nom_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_fecha_creacion', models.DateField()),
                ('nom_tipo_pago', models.CharField(max_length=200)),
                ('nom_periodo_pago', models.DateField()),
                ('nom_dias_trabajados', models.IntegerField()),
                ('nom_cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario', to_field='cedula')),
            ],
        ),
    ]
